### ISSUE TITLE
Clear feedback buffer when changing the chain

### ISSUE THREAD

**Issue by mguentner** [dronus/VisSynthWeb#3]
When changing to an another chain, the feedback buffer should be cleared or
old frames end up in the output.

Example:
When executing a chain that uses the feedback buffer and
one changes to a chain without a feedbackIn effect and then changes back
to the first chain after lets say one hour, the old frames recorded during
the first run are still in the buffer and will be used during the first few seconds.
This probably produces unwanted results ;)

**Comment by dronus** [comment]
But sometimes this produces quite nice results...
For example, the `timeshift` buffer is quite large and often contains images from quite old effects, and thus often lead to unexpected effects. The one-frame `feedbackIn` buffer however is used in a slow-blended fashion in many of the preset chains, and this gives quite nice transition effects if switching over from one effect using it to another (eg. the `reaction` and `smoothlife` based effects for example).
The `motion` effect background accumulator buffer for example is most likely to be kept on chains switching.
So without being optionaly, I would delete the timeshift buffer, keep the motion buffer and I am unsure about the feedback buffer. 
It would be cool to have this feature optionally, but the current option setup system (using adjustment effects - the dark blue ones) is a little poor. It has the great benefit of serving KISS as it does not need any UI or data structures on it's own, but is hard to get if more and more settings are added I guess.

So for now, I just try to implement an unoptionally clear of timeshift and feedback buffers first, let's see how that works.

**Comment by dronus** [comment]
For simplicity, we just programatically clear all textures on chain swap. I will check out this at the next live show usage and report back.

**Comment by dronus** [comment]
Maybe it would be an cool idea to have the filters clear the buffer themselves if wanted. The feedbackIn effect could then have an parameter to switch this behavior on a per-chain basis. For example the default chains `spectro tunnel`, `spectro road` and `road roof`nicely continue the motion of each other on switching, while appearing black in the first place if the buffers are cleared. Those chains may keep the buffers. The `timeshift` effect may keep it's buffer too if one like to switch between several almost-likely looking chains all using it.
So allowing the user to decide on buffer clear on every effect instance would be quite cool I guess.

**Comment by dronus** [comment]
#6 now enables to clear individual buffers on chain switch, if the effect has the `clear_on_switch` parameter set to 1. Needs updating of old chains to benefit from though, but doesn't change anything by default this way.

**Comment by dronus** [comment]
Merged into master.
